---
name: Catalyst-Plugin-Scheduler
version: 0.08
author:
  - 'Andy Grundman, <andy@hybridized.org>'
abstract: Schedule events to run in a cron-like fashion
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.61
  DateTime::Event::Cron: 0
  Set::Scalar: 0
  Storable: 0
  YAML: 0
provides:
  Catalyst::Plugin::Scheduler:
    file: lib/Catalyst/Plugin/Scheduler.pm
    version: 0.08
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
