--- #YAML:1.0
name: Catalyst-Plugin-Scheduler
version: 0.07
author:
  - Andy Grundman, <andy@hybridized.org>
abstract: Schedule events to run in a cron-like fashion
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
